let
    Request = (Pagina as number) => 
    let 
        body =
        "{
        ""call"":""ListarContasReceber"",
        ""app_key"": """ & Text.From(app_key) & """,
        ""app_secret"": """ & Text.From(app_secret) & """,
        ""param"":[
            {
                ""pagina"":"&Text.From(Pagina)&",
                ""registros_por_pagina"":50
            }
            ]
        }" 
    ,
    Consulta = 
        Json.Document(
            Web.Contents(
                "https://app.omie.com.br",
                [
                    RelativePath="api/v1/financas/contareceber/",
                    Headers=[#"Content-Type"="application/json"],
                    Content=Text.ToBinary(body)
                ]
            )
        )
   
  in
    Consulta,
    Tabela = Table.FromRecords({[Pagina=1]}),
    AlterarTipo = Table.TransformColumnTypes(Tabela,{{"Pagina", Int64.Type}}),
    InvocarFuncao01 = Table.AddColumn(AlterarTipo, "Tabela", each Request([Pagina])),
    Tabela1 = InvocarFuncao01{0}[Tabela],
    Paginas = Tabela1[total_de_paginas],
    ListaPaginas = Table.FromList( List.Generate( () => 1, each _ <= Paginas , each _ +1 ), Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    InvocarFuncao02 = Table.AddColumn(ListaPaginas, "Tabela", each Request([Column1])),
    #"Removed Columns" = Table.RemoveColumns(InvocarFuncao02,{"Column1"}),
    #"Expanded {0}" = Table.ExpandRecordColumn(#"Removed Columns", "Tabela", {"conta_receber_cadastro"}, {"conta_receber_cadastro"}),
    #"Expanded {0}1" = Table.ExpandListColumn(#"Expanded {0}", "conta_receber_cadastro"),
    #"Expanded {0}2" = Table.ExpandRecordColumn(#"Expanded {0}1", "conta_receber_cadastro", {"bloqueado", "bloquear_baixa", "boleto", "categorias", "codigo_categoria","codigo_cliente_fornecedor","codigo_lancamento_integracao", "codigo_lancamento_omie","codigo_projeto","codigo_tipo_documento","data_emissao","data_previsao","data_registro","data_vencimento","distribuicao", "id_conta_corrente","id_origem","info","numero_parcela","observacao","retem_cofins","retem_csll","retem_ir","retem_iss","retem_pis", "status_titulo", "tipo_agrupamento","valor_cofins", "valor_csll", "valor_documento","valor_ir", "valor_iss",  "valor_pis"}),
    #"Expanded distribuicao" = Table.ExpandListColumn(#"Expanded {0}2", "distribuicao"),
    #"Expanded distribuicao1" = Table.ExpandRecordColumn(#"Expanded distribuicao", "distribuicao", {"cCodDep", "cDesDep", "nPerDep", "nValDep"}, {"cCodDep", "cDesDep", "nPerDep", "nValDep"}),
    #"Índice Adicionado1" = Table.AddIndexColumn(#"Expanded distribuicao1", "Índice", 1, 1, Int64.Type),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Índice Adicionado1",{"Índice", "bloqueado", "bloquear_baixa", "boleto", "categorias", "codigo_categoria", "codigo_cliente_fornecedor", "codigo_lancamento_integracao", "codigo_lancamento_omie","codigo_projeto", "codigo_tipo_documento", "data_emissao", "data_previsao", "data_registro", "data_vencimento", "cCodDep", "cDesDep", "nPerDep", "nValDep", "id_conta_corrente", "id_origem", "info", "numero_parcela", "observacao", "retem_cofins", "retem_csll", "retem_ir", "retem_iss", "retem_pis", "status_titulo", "tipo_agrupamento", "valor_cofins", "valor_csll", "valor_documento", "valor_ir", "valor_iss", "valor_pis"}),
    #"categorias Expandido" = Table.ExpandListColumn(#"Colunas Reordenadas2", "categorias"),
    #"categorias Expandido1" = Table.ExpandRecordColumn(#"categorias Expandido", "categorias", {"codigo_categoria", "percentual", "valor"}, {"codigo_categoria.1", "percentual", "valor"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"categorias Expandido1",{{"percentual", Percentage.Type}, {"valor", Currency.Type}, {"data_emissao", type date}, {"data_previsao", type date}, {"data_registro", type date}, {"data_vencimento", type date}, {"nPerDep", Percentage.Type}, {"nValDep", Currency.Type}}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Tipo Alterado",{{"valor_cofins", Currency.Type}, {"valor_csll", Currency.Type}, {"valor_documento", Currency.Type}, {"valor_ir", Currency.Type}, {"valor_iss", Currency.Type}, {"valor_pis", Currency.Type}}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"boleto"}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas",{"bloquear_baixa", "bloqueado", "codigo_categoria.1", "percentual", "valor", "codigo_categoria", "codigo_cliente_fornecedor", "codigo_lancamento_integracao", "codigo_lancamento_omie","codigo_projeto", "codigo_tipo_documento", "data_emissao", "data_previsao", "data_registro", "data_vencimento", "cCodDep", "cDesDep", "nPerDep", "nValDep", "id_conta_corrente", "id_origem", "info", "numero_parcela", "observacao", "retem_cofins", "retem_csll", "retem_ir", "retem_iss", "retem_pis", "status_titulo", "tipo_agrupamento", "valor_cofins", "valor_csll", "valor_documento", "valor_ir", "valor_iss", "valor_pis"}),
    #"Índice Adicionado" = Table.AddIndexColumn(#"Colunas Reordenadas", "Índice.1", 0, 0, Int64.Type),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Índice Adicionado",{"Índice.1", "Índice", "bloquear_baixa", "bloqueado", "codigo_categoria.1", "percentual", "valor", "codigo_categoria", "codigo_cliente_fornecedor", "codigo_lancamento_integracao", "codigo_lancamento_omie","codigo_projeto", "codigo_tipo_documento", "data_emissao", "data_previsao", "data_registro", "data_vencimento", "cCodDep", "cDesDep", "nPerDep", "nValDep", "id_conta_corrente", "id_origem", "info", "numero_parcela", "observacao", "retem_cofins", "retem_csll", "retem_ir", "retem_iss", "retem_pis", "status_titulo", "tipo_agrupamento", "valor_cofins", "valor_csll", "valor_documento", "valor_ir", "valor_iss", "valor_pis"}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Reordenadas1",{{"Índice.1", type text}}),
    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado2","0","Receitas",Replacer.ReplaceText,{"Índice.1"}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Valor Substituído",{{"Índice.1", "Tipo de Conta"}, {"cCodDep", "Código Departamento"}, {"cDesDep", "Descrição Departamento"}, {"nPerDep", "Percentual Departamento"}, {"nValDep", "Valor Departamento"}}),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"percentual", type text}})
in
    #"Tipo Alterado3"