let
    Request = (Pagina as number) => 
    let 
        body =
        "{
        ""call"":""ListarCategorias"",
        ""app_key"": """ & Text.From(app_key) & """,
        ""app_secret"": """ & Text.From(app_secret) & """,
        ""param"":[
            {
                ""pagina"":"&Text.From(Pagina)&",
                ""registros_por_pagina"":100
            }
            ]
        }" 
    ,
    Consulta = 
        Json.Document(
            Web.Contents(
                "https://app.omie.com.br",
                [
                    RelativePath="api/v1/geral/categorias/",
                    Headers=[#"Content-Type"="application/json"],
                    Content=Text.ToBinary(body)
                ]
            )
        )
    in
    Consulta,
    Tabela = Table.FromRecords({[Pagina=1]}),
    AlterarTipo = Table.TransformColumnTypes(Tabela,{{"Pagina", Int64.Type}}),
    InvocarFuncao01 = Table.AddColumn(AlterarTipo, "Tabela", each Request([Pagina])),
    Tabela1 = InvocarFuncao01{0}[Tabela],
    Paginas = Tabela1[total_de_paginas],
    ListaPaginas = Table.FromList( List.Generate( () => 1, each _ <= Paginas , each _ +1 ), Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    InvocarFuncao02 = Table.AddColumn(ListaPaginas, "Tabela", each Request([Column1])),
    #"Removed Columns" = Table.RemoveColumns(InvocarFuncao02,{"Column1"}),
    #"Expanded {0}" = Table.ExpandRecordColumn(#"Removed Columns", "Tabela", {"categoria_cadastro"}, {"categoria_cadastro"}),
    #"Expanded {0}1" = Table.ExpandListColumn(#"Expanded {0}", "categoria_cadastro"),
    #"Expanded {0}2" = Table.ExpandRecordColumn(#"Expanded {0}1", "categoria_cadastro", {"categoria_superior", "codigo", "codigo_dre", "conta_despesa", "conta_inativa","conta_receita","dadosDRE", "definida_pelo_usuario","descricao","descricao_padrao","id_conta_contabil","nao_exibir","natureza","tag_conta_contabil", "totalizadora","transferencia"}),
    #"dadosDRE Expandido" = Table.ExpandRecordColumn(#"Expanded {0}2", "dadosDRE", {"codigoDRE", "descricaoDRE", "naoExibirDRE", "nivelDRE", "sinalDRE", "totalizaDRE"}, {"codigoDRE", "descricaoDRE", "naoExibirDRE", "nivelDRE", "sinalDRE", "totalizaDRE"})
in
    #"dadosDRE Expandido"