let
    Request = (Pagina as number) => 
    let 
        body =
        "{
        ""call"":""ListarClientes"",
        ""app_key"": """ & Text.From(app_key) & """,
        ""app_secret"": """ & Text.From(app_secret) & """,
        ""param"":[
            {
                ""pagina"":"&Text.From(Pagina)&",
                ""registros_por_pagina"":100
            }
            ]
        }" 
    ,
    Consulta = 
        Json.Document(
            Web.Contents(
                "https://app.omie.com.br",
                [
                    RelativePath="api/v1/geral/clientes/",
                    Headers=[#"Content-Type"="application/json"],
                    Content=Text.ToBinary(body)
                ]
            )
        )
in

Consulta,
    Tabela = Table.FromRecords({[Pagina=1]}),
    AlterarTipo = Table.TransformColumnTypes(Tabela,{{"Pagina", Int64.Type}}),
    InvocarFuncao01 = Table.AddColumn(AlterarTipo, "Tabela", each Request([Pagina])),
    Tabela1 = InvocarFuncao01{0}[Tabela],
    Paginas = Tabela1[total_de_paginas],
    ListaPaginas = Table.FromList( List.Generate( () => 1, each _ <= Paginas , each _ +1 ), Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    InvocarFuncao02 = Table.AddColumn(ListaPaginas, "Tabela", each Request([Column1])),
    #"Removed Columns" = Table.RemoveColumns(InvocarFuncao02,{"Column1"}),
    #"Expanded {0}" = Table.ExpandRecordColumn(#"Removed Columns", "Tabela", {"clientes_cadastro"}, {"clientes_cadastro"}),
    #"Expanded {0}1" = Table.ExpandListColumn(#"Expanded {0}", "clientes_cadastro"),
    #"Expanded {0}2" = Table.ExpandRecordColumn(#"Expanded {0}1", "clientes_cadastro", {"bairro", "bloquear_faturamento", "cep", "cidade", "cidade_ibge","cnpj_cpf","codigo_cliente_integracao", "codigo_cliente_omie","codigo_pais","complemento","dadosBancarios","endereco","enderecoEntrega","endereco_numero", "estado","exterior","inativo","info","inscricao_estadual","inscricao_municipal","nome_fantasia","optante_simples_nacional","pessoa_fisica","razao_social", "recomendacoes", "tags"}),
    #"tags Expandido" = Table.ExpandListColumn(#"Expanded {0}2", "tags"),
    #"tags Expandido1" = Table.ExpandRecordColumn(#"tags Expandido", "tags", {"tag"}, {"tag"}),
    #"Personalização Adicionada" = Table.AddColumn(#"tags Expandido1", "DataAtualizacao", each DateTime.LocalNow()),
    #"Duplicatas Removidas" = Table.Distinct(#"Personalização Adicionada", {"codigo_cliente_omie"})
in
    #"Duplicatas Removidas"